app/home/__init__.py
# -*- coding: utf-8 -*-
# @Time    : 2019/10/21 上午1:45
# @Author  : Thanlon
# @Wechat：18512152005
# @Email   : thanlon@sina.com
# @File    : __init__.py
# @Software: PyCharm
from flask import Blueprint

home_bp = Blueprint('home', __name__)
from .views import user,index,robots,feedback,mall,about_website,disclaimer,blueprint,contact_us

app/home/views/about_website.py
# -*- coding: utf-8 -*-
# @Time    : 2019/12/25 下午3:46
# @Author  : Thanlon
# @Wechat：18512152005
# @Email   : thanlon@sina.com
# @File    : about_website.py
# @Software: PyCharm
from .. import home_bp
from flask import render_template
@home_bp.route('/v1/about-website')
def about_website():
    return render_template('/home/about-website.html')

app/home/views/blueprint.py
# -*- coding: utf-8 -*-
# @Time    : 2019/12/25 下午3:46
# @Author  : Thanlon
# @Wechat：18512152005
# @Email   : thanlon@sina.com
# @File    : about_website.py
# @Software: PyCharm
from .. import home_bp
from flask import render_template
@home_bp.route('/v1/blueprint')
def blueprint():
    return render_template('/home/blueprint.html')

app/home/views/contact_us.py
# -*- coding: utf-8 -*-
# @Time    : 2019/12/25 下午3:46
# @Author  : Thanlon
# @Wechat：18512152005
# @Email   : thanlon@sina.com
# @File    : about_website.py
# @Software: PyCharm
from .. import home_bp
from flask import render_template


@home_bp.route('/v1/contact-us')
def contact_us():
    return render_template('/home/contact_us.html')

app/home/views/disclaimer.py
# -*- coding: utf-8 -*-
# @Time    : 2019/12/25 下午3:46
# @Author  : Thanlon
# @Wechat：18512152005
# @Email   : thanlon@sina.com
# @File    : about_website.py
# @Software: PyCharm
from .. import home_bp
from flask import render_template
@home_bp.route('/v1/disclaimer')
def disclaimer():
    return render_template('/home/disclaimer.html')

app/home/views/feedback.py
# -*- coding: utf-8 -*-
# @Time    : 2019/10/24 下午3:25
# @Author  : Thanlon
# @Wechat：18512152005
# @Email   : thanlon@sina.com
# @File    : feedback.py
# @Software: PyCharm
from .. import home_bp
from flask import render_template


@home_bp.route('/v1/feedback')
def feedback():
    return render_template('/home/feedback.html')

app/home/views/index.py
# -*- coding: utf-8 -*-
# @Time    : 2019/10/23 上午12:59
# @Author  : Thanlon
# @Wechat：18512152005
# @Email   : thanlon@sina.com
# @File    : index.py
# @Software: PyCharm
from .. import home_bp
from flask import render_template


@home_bp.route('/')
def index():
    return render_template('/home/index.html')

app/home/views/login_decorator.py
# -*- coding: utf-8 -*-
# @Time    : 2019/11/10 上午11:48
# @Author  : Thanlon
# @Wechat：18512152005
# @Email   : thanlon@sina.com
# @File    : de.py
# @Software: PyCharm
from functools import wraps
from flask import request, session, redirect, url_for

def user_login_rule(foo):
    @wraps(foo)
    def decorated_function(*args, **kwargs):
        if 'name' not in session:  # if not session.get('user_info'):
            return redirect(url_for('home_bp.index', next=request.url))
        return foo(*args, **kwargs)

    return decorated_function

app/home/views/mall.py
# -*- coding: utf-8 -*-
# @Time    : 2019/10/24 下午5:31
# @Author  : Thanlon
# @Wechat：18512152005
# @Email   : thanlon@sina.com
# @File    : mall.py
# @Software: PyCharm
from .. import home_bp
from flask import render_template
@home_bp.route('/v1/mall')
def mall():
    return render_template('/home/mall.html')

app/home/views/robots.py
# -*- coding: utf-8 -*-
# @Time    : 2019/10/23 上午12:20
# @Author  : Thanlon
# @Wechat：18512152005
# @Email   : thanlon@sina.com
# @File    : robots.py
# @Software: PyCharm
from .. import home_bp
from flask import render_template


@home_bp.route('/robots.txt')
def robots():
    return render_template('robots.txt')

app/home/views/user.py
# -*- coding: utf-8 -*-
# @Time    : 2019/10/21 上午2:03
# @Author  : Thanlon
# @Wechat：18512152005
# @Email   : thanlon@sina.com
# @File    : user.py
# @Software: PyCharm
from .. import home_bp
from flask import request, session, redirect, url_for
from app.models import connect_db, Users, UsersLoginLogs
from random import randint
import requests
from sqlalchemy import or_
from app.utils.md5 import md5


@home_bp.route('/v1/send_code', methods=['GET', 'POST'])
def send_code():
    msg = None
    random_verify_code = str(randint(100000, 999999))
    session['random_verify_code'] = random_verify_code
    # print(session['random_verify_code'],type(session['random_verify_code']))
    mobile_number = request.form.get('mobile_number')
    # print(mobile_number)
    req_url = "http://api.feige.ee/SmsService/Send"
    data = {"Account": "18937693205", "Pwd": "61a8ea729e25f1cf745066d33",
            "Content": "验证码:" + random_verify_code + "。您正在使用短信验证码注册登录功能，该验证码仅用于身份校验，请勿泄露给他人使用。",
            "Mobile": mobile_number, "SignId": 106861}
    response = requests.post(req_url, data=data)
    # print(response.content)
    msg = 'ok'
    return msg


@home_bp.route('/v1/register/', methods=['POST'])
def register():
    if request.method == 'POST':
        msg = None
        verify_code = request.form.get('verify_code')
        # print(verify_code, session['random_verify_code'])
        if verify_code != session['random_verify_code']:
            msg = 'verify_code_err'
            return msg
        name = request.form.get('name')
        mobile_number = request.form.get('mobile_number')
        pwd = request.form.get('pwd')
        pwd = md5(pwd)
        session_ = connect_db()
        name_count = ret = session_.query(Users).filter(Users.mobile_number == mobile_number).count()
        if name_count > 0:
            msg = 'name_error'
            return msg
        try:
            user_obj = Users(
                name=name,
                pwd=pwd,
                mobile_number=mobile_number
            )
            session_.add(user_obj)
            session_.commit()
            session_.close()
        except Exception as e:
            msg = 'db_error'
            return msg
        msg = 'ok'
        return msg
    return '不允许Get请求！'


@home_bp.route('/v1/login/', methods=['POST'])
def login():
    if request.method == 'POST':
        msg = None
        name = request.form.get('name')
        pwd = request.form.get('pwd')
        pwd = md5(pwd)
        # print(name, pwd)
        session_ = connect_db()
        user_obj = session_.query(Users).filter(or_(Users.name == name, Users.mobile_number == name),
                                                Users.pwd == pwd)
        count = user_obj.count()
        id = user_obj.first().id
        name = user_obj.first().name
        # print(count, id, name)
        session['id'] = id
        session['name'] = name
        login_logs_obj = UsersLoginLogs(
            ip=request.remote_addr,
            users_id=id,
        )
        session_.add(login_logs_obj)
        session_.commit()
        session_.close()
        if count > 0:
            msg = 'ok'
            return msg
        else:
            msg = 'error'
            return msg
    return '不允许Get请求！'


@home_bp.route('/v1/logout/')
def logout():
    session.pop('name', None)
    return redirect('/')

app/templates/home/about-website.html
{% extends 'home/layout.html' %}
{% block css %}
{% endblock %}
{% block content %}
<div class="container" style="margin-top: 70px;padding: 0">
    <div class="row">
        <div class="col-md-12" style="padding:5px;">
            <ol class="breadcrumb" style="margin-bottom: 0;padding: 10px">
                <li><a href="{{url_for('home.index')}}">首页</a></li>
                <li class="active">关于本站</a></li>
            </ol>
            <div class="col-md-3" style="padding: 0">
                <div class="panel panel-default" style="padding-bottom: 0">
                    <!--                <div class="panel-heading">关于本站</div>-->
                    <div class="panel-body">
                        <ul class="list-group" style="margin-bottom: 0">
                            <a href="" class="list-group-item btn"
                               style="font-weight: bold;background: #ddd">
                                &nbsp;&nbsp;关于本站
                            </a>
                            <a href="" class="list-group-item btn"
                               style="font-weight: bold;">
                                &nbsp;&nbsp;免责申明
                            </a>
                            <a href="" class="list-group-item btn"
                               style="font-weight: bold;">
                                &nbsp;&nbsp;本站蓝图
                            </a>
                            <a href="" class="list-group-item btn"
                               style="font-weight: bold;">
                                &nbsp;&nbsp;联系我们
                            </a>
                            <!--                            <a href="" class="list-group-item btn"-->
                            <!--                               style="font-weight: bold;">-->
                            <!--                                &nbsp;&nbsp;留言板-->
                            <!--                            </a>-->
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-md-9" style="padding-right: 0">
                <!--            <div class="panel panel-primary">-->
                <!--                <div class="panel-heading">-->
                <!--                    / 关于本站 / 关于运营-联系方式-->
                <!--                </div>-->
                <!--            </div>-->
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h5>
                            <spqn class="glyphicon glyphicon-user"></spqn>
                            WeChat：18512152005
                        </h5>
                        <h5>
                            <spqn class="glyphicon glyphicon-user"></spqn>
                            QQ：3330447288
                        </h5>
                        <h5>
                            <span class="glyphicon glyphicon-envelope"></span>
                            E-mail&nbsp;：thanlon@sina.com
                        </h5>
                        <h5>
                            <spqn class="glyphicon glyphicon-link"></spqn>
                            博客地址：<a href="https://blog.csdn.net/Thanlon"
                                    target="_blank">https://blog.csdn.net/Thanlon</a>
                        </h5>
                    </div>
                    {% for v in range(18)%}<br>{% endfor%}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block js %}
{% endblock %}

app/templates/home/about_website.html
{% extends 'home/layout.html' %}
{% block css %}
{% endblock %}
{% block content %}
<div class="container" style="margin-top: 70px;padding: 0">
    <div class="row">
        <div class="col-md-12" style="padding:5px;">
            <ol class="breadcrumb" style="margin-bottom: 0;padding: 10px">
                <li><a href="{{url_for('home.index')}}">首页</a></li>
                <li class="active">关于本站</a></li>
            </ol>
            <div class="col-md-3" style="padding: 0">
                <div class="panel panel-default" style="padding-bottom: 0">
                    <!--                <div class="panel-heading">关于本站</div>-->
                    <div class="panel-body">
                        <ul class="list-group" style="margin-bottom: 0">
                            <a href="{{url_for('home.about_website')}}" class="list-group-item btn"
                               style="font-weight: bold;background: #ddd">
                                &nbsp;&nbsp;关于本站
                            </a>
                            <a href="{{url_for('home.disclaimer')}}" class="list-group-item btn"
                               style="font-weight: bold;">
                                &nbsp;&nbsp;免责申明
                            </a>
                            <a href="{{url_for('home.blueprint')}}" class="list-group-item btn"
                               style="font-weight: bold;">
                                &nbsp;&nbsp;本站蓝图
                            </a>
                            <a href="{{url_for('home.contact_us')}}" class="list-group-item btn"
                               style="font-weight: bold;">
                                &nbsp;&nbsp;联系我们
                            </a>
                            <!--                            <a href="" class="list-group-item btn"-->
                            <!--                               style="font-weight: bold;">-->
                            <!--                                &nbsp;&nbsp;留言板-->
                            <!--                            </a>-->
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-md-9" style="padding-right: 0">
                <!--            <div class="panel panel-primary">-->
                <!--                <div class="panel-heading">-->
                <!--                    / 关于本站 / 关于运营-联系方式-->
                <!--                </div>-->
                <!--            </div>-->
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h5>1、本站面向全国互联网科技爱好者，是互联网信息资讯共享的友好平台，共享优质的互联网信息资讯、技术文章、源代码项目等……</h5>
                        <h5>2、项目源码由已申请开发者权限的用户上传，有的需要收取少量费用</h5>
                        <h5>3、开发者上传的项目源码，需要通过本平台的审核才能被用户下载</h5>
                        <h5>4、开发者上传的项目源码未通过审核，平台将予以驳回，不存储开发者未通过审核的资源</h5>
                    </div>
                    {% for v in range(18)%}<br>{% endfor%}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block js %}
{% endblock %}

app/templates/home/blueprint.html
{% extends 'home/layout.html' %}
{% block css %}
{% endblock %}
{% block content %}
<div class="container" style="margin-top: 70px;padding: 0">
    <div class="row">
        <div class="col-md-12" style="padding:5px;">
            <ol class="breadcrumb" style="margin-bottom: 0;padding: 10px">
                <li><a href="{{url_for('home.index')}}">首页</a></li>
                <li class="active">本站蓝图</a></li>
            </ol>
            <div class="col-md-3" style="padding: 0">
                <div class="panel panel-default" style="padding-bottom: 0">
                    <!--                <div class="panel-heading">关于本站</div>-->
                    <div class="panel-body">
                        <ul class="list-group" style="margin-bottom: 0">
                            <a href="{{url_for('home.about_website')}}" class="list-group-item btn"
                               style="font-weight: bold;">
                                &nbsp;&nbsp;关于本站
                            </a>
                            <a href="{{url_for('home.disclaimer')}}" class="list-group-item btn"
                               style="font-weight: bold;">
                                &nbsp;&nbsp;免责申明
                            </a>
                            <a href="{{url_for('home.blueprint')}}" class="list-group-item btn"
                               style="font-weight: bold;background: #ddd">
                                &nbsp;&nbsp;本站蓝图
                            </a>
                            <a href="{{url_for('home.contact_us')}}" class="list-group-item btn"
                               style="font-weight: bold;">
                                &nbsp;&nbsp;联系我们
                            </a>
                            <!--                            <a href="" class="list-group-item btn"-->
                            <!--                               style="font-weight: bold;">-->
                            <!--                                &nbsp;&nbsp;留言板-->
                            <!--                            </a>-->
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-md-9" style="padding-right: 0">
                <!--            <div class="panel panel-primary">-->
                <!--                <div class="panel-heading">-->
                <!--                    / 关于本站 / 关于运营-联系方式-->
                <!--                </div>-->
                <!--            </div>-->
                <div class="panel panel-default">
                    <div class="panel-body">
                        <span class="glyphicon glyphicon-arrow-up"></span> 2019年5月14日：版本号:1.1.0.190513_alpha<br><br>
                        <span class="glyphicon glyphicon-arrow-up"></span> 2019年4月14日：版本号:1.1.0.190414_alpha<br><br>
                        <span class="glyphicon glyphicon-arrow-up"></span> 2019年4月11日：版本号:1.1.0.190411_alpha<br><br>
                        <span class="glyphicon glyphicon-arrow-up"></span> 2019年4月7日：版本号1.1.0.190407_alpha <br><br>
                        <span class="glyphicon glyphicon-arrow-up"></span> 2019年4月2日：版本号:1.1.0.190402_alpha <br> <br>
                        <span class="glyphicon glyphicon-arrow-up"></span> 2019年3月24日：版本号:1.1.0.190324_alpha
                    </div>
                    {% for v in range(18)%}<br>{% endfor%}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block js %}
{% endblock %}

app/templates/home/contact_us.html
{% extends 'home/layout.html' %}
{% block css %}
{% endblock %}
{% block content %}
<div class="container" style="margin-top: 70px;padding: 0">
    <div class="row">
        <div class="col-md-12" style="padding:5px;">
            <ol class="breadcrumb" style="margin-bottom: 0;padding: 10px">
                <li><a href="{{url_for('home.index')}}">首页</a></li>
                <li class="active">联系我们</a></li>
            </ol>
            <div class="col-md-3" style="padding: 0">
                <div class="panel panel-default" style="padding-bottom: 0">
                    <!--                <div class="panel-heading">关于本站</div>-->
                    <div class="panel-body">
                        <ul class="list-group" style="margin-bottom: 0">
                            <a href="{{url_for('home.about_website')}}" class="list-group-item btn"
                               style="font-weight: bold;">
                                &nbsp;&nbsp;关于本站
                            </a>
                            <a href="{{url_for('home.disclaimer')}}" class="list-group-item btn"
                               style="font-weight: bold;">
                                &nbsp;&nbsp;免责申明
                            </a>
                            <a href="{{url_for('home.blueprint')}}" class="list-group-item btn"
                               style="font-weight: bold;">
                                &nbsp;&nbsp;本站蓝图
                            </a>
                            <a href="{{url_for('home.contact_us')}}" class="list-group-item btn"
                               style="font-weight: bold;background: #ddd">
                                &nbsp;&nbsp;联系我们
                            </a>
                            <!--                            <a href="" class="list-group-item btn"-->
                            <!--                               style="font-weight: bold;">-->
                            <!--                                &nbsp;&nbsp;留言板-->
                            <!--                            </a>-->
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-md-9" style="padding-right: 0">
                <!--            <div class="panel panel-primary">-->
                <!--                <div class="panel-heading">-->
                <!--                    / 关于本站 / 关于运营-联系方式-->
                <!--                </div>-->
                <!--            </div>-->
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h5>
                            <spqn class="glyphicon glyphicon-user"></spqn>
                            WeChat：18512152005
                        </h5>
                        <h5>
                            <spqn class="glyphicon glyphicon-user"></spqn>
                            QQ：3330447288
                        </h5>
                        <h5>
                            <span class="glyphicon glyphicon-envelope"></span>
                            E-mail&nbsp;：thanlon@sina.com
                        </h5>
                        <h5>
                            <spqn class="glyphicon glyphicon-link"></spqn>
                            博客地址：<a href="https://blog.csdn.net/Thanlon"
                                    target="_blank">https://blog.csdn.net/Thanlon</a>
                        </h5>
                    </div>
                    {% for v in range(18)%}<br>{% endfor%}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block js %}
{% endblock %}

app/templates/home/disclaimer.html
{% extends 'home/layout.html' %}
{% block css %}
{% endblock %}
{% block content %}
<div class="container" style="margin-top: 70px;padding: 0">
    <div class="row">
        <div class="col-md-12" style="padding:5px;">
            <ol class="breadcrumb" style="margin-bottom: 0;padding: 10px">
                <li><a href="{{url_for('home.index')}}">首页</a></li>
                <li class="active">免责申明</a></li>
            </ol>
            <div class="col-md-3" style="padding: 0">
                <div class="panel panel-default" style="padding-bottom: 0">
                    <!--                <div class="panel-heading">关于本站</div>-->
                    <div class="panel-body">
                        <ul class="list-group" style="margin-bottom: 0">
                            <a href="{{url_for('home.about_website')}}" class="list-group-item btn"
                               style="font-weight: bold;">
                                &nbsp;&nbsp;关于本站
                            </a>
                            <a href="{{url_for('home.disclaimer')}}" class="list-group-item btn"
                               style="font-weight: bold;background: #ddd">
                                &nbsp;&nbsp;免责申明
                            </a>
                            <a href="{{url_for('home.blueprint')}}" class="list-group-item btn"
                               style="font-weight: bold;">
                                &nbsp;&nbsp;本站蓝图
                            </a>
                            <a href="{{url_for('home.contact_us')}}" class="list-group-item btn"
                               style="font-weight: bold;">
                                &nbsp;&nbsp;联系我们
                            </a>
                            <!--                            <a href="" class="list-group-item btn"-->
                            <!--                               style="font-weight: bold;">-->
                            <!--                                &nbsp;&nbsp;留言板-->
                            <!--                            </a>-->
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-md-9" style="padding-right: 0">
                <!--            <div class="panel panel-primary">-->
                <!--                <div class="panel-heading">-->
                <!--                    / 关于本站 / 关于运营-联系方式-->
                <!--                </div>-->
                <!--            </div>-->
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h5>1、用户用于注册的个人相关信息，本站均通过加密算法进行加密，切实保护用户的隐私、保障用户的合法权益</h5>
                        <h5>2、请用户规范自己的行为，发表文章或评论中切不可出现反政治、有暴力倾向、恐吓、色情等的危害公共安全的言论</对于违反></h5>
                        <h5>3、特此申明：注册成为本站用户即表示您已同意本协议</h5>
                    </div>
                    {% for v in range(18)%}<br>{% endfor%}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block js %}
{% endblock %}

app/templates/home/feedback.html
{% extends 'home/layout.html' %}
{% block css %}

{% endblock %}
{% block content %}
<div class="container" style="margin-top: 70px;padding: 0">
    <div class="row">
        <!--        <div class="col-md-3" style="padding: 0;padding-right: 5px">-->
        <!--            <div class="panel ">-->
        <!--                <div class="panel-heading">关于本站</div>-->
        <!--                <div class="panel-body">-->
        <!--                    <ul class="list-group">-->
        <!--                        <a href="" class="list-group-item btn "-->
        <!--                           style="font-weight: bold;">-->
        <!--                            &nbsp;&nbsp;用户协议-->
        <!--                        </a>-->
        <!--                        <a href="" class="list-group-item btn"-->
        <!--                           style="font-weight: bold;">-->
        <!--                            &nbsp;&nbsp;免责申明-->
        <!--                        </a>-->
        <!--                        <a href="" class="list-group-item btn"-->
        <!--                           style="font-weight: bold;">-->
        <!--                            &nbsp;&nbsp;本站蓝图-->
        <!--                        </a>-->
        <!--                        <a href="" class="list-group-item btn"-->
        <!--                           style="font-weight: bold;">-->
        <!--                            &nbsp;&nbsp;联系运营-->
        <!--                        </a>-->
        <!--                        <a href="" class="list-group-item btn"-->
        <!--                           style="font-weight: bold;background: #ddd">-->
        <!--                            &nbsp;&nbsp;留言板-->
        <!--                        </a>-->
        <!--                    </ul>-->
        <!--                </div>-->
        <!--            </div>-->
        <!--        </div>-->
        <!--        <div class="col-md-12" style="padding: 0;margin-top: 8px">-->
        <!--            <img src="holder.js/1200x100" class="img-responsive" alt="">-->
        <!--        </div>-->
        <div class="col-md-12" style="padding:5px;">
            <ol class="breadcrumb" style="margin-bottom: 0;padding: 10px">
                <li><a href="{{url_for('home.index')}}">首页</a></li>
                <li class="active">用户反馈</a></li>
            </ol>
            <div class="panel panel-default">
                <div class="panel-body">
                    <h5>
                        <span class="glyphicon glyphicon-folder-close"></span>
                        留言反馈
                        <hr>
                        <div>
                            <p>欢迎来到39毕设网，如果有什么问题，可直接在下面留言区留言反馈!</p>
                            <br>
                            <p>如果您在使用本站的过程中遇到问题，可加QQ群进行交流!</p>
                            <br>
                            <p>如果有广告、投稿等合作意向，可加@小奈微信：18512152005(加好友请说明来意)!</p>
                        </div>
                    </h5>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-body">
                    {% for msg in get_flashed_messages(category_filter=["okey"]) %}
                    <div class="alert alert-success alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                            ×
                        </button>
                        {{ msg }}
                    </div>
                    {% endfor %}
                    {% for msg in get_flashed_messages(category_filter=["error"]) %}
                    <div class="alert alert-danger alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                            ×
                        </button>
                        <h4><i class="icon fa fa-ban"></i> 操作失败</h4>
                        {{ msg }}
                    </div>
                    {% endfor %}
                    <form role="form" style="margin-bottom:6px;" method="post">
                        <div class="form-group">
                            <div>
                                <label for="input_content"></label><br>

                            </div>


                        </div>
                        <div class="form-group">

                        </div>
                    </form>
                    <div class="breadcrumb">
                        <li>全部评论</li>
                    </div>
                    <div class="col-md-12" style="margin-top: 3px;padding: 0">
                        <div class="panel panel-default">
                            <div class="panel-heading">楼&nbsp;留言于</div>
                            <div class="panel-body"></div>
                        </div>
                    </div>
                </div>
                <div class="panel-body">
                    <button type="button" id="myButton" data-loading-text="Loading..." class="btn btn-primary"
                            autocomplete="off">
                        加载更多留言...
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block js %}
{% endblock %}